#cloud-config
package_update: true
package_upgrade: true

packages:
  - iptables-persistent

runcmd:
  - |
    # enable IPv4 forwarding
    echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-nat-gateway.conf
    echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-nat-gateway.conf
    sysctl -p /etc/sysctl.d/99-nat-gateway.conf
    # update i[tables and save configuration
    iptables -t nat -A POSTROUTING -s '${private_subnet}' -o eth0 -j MASQUERADE
    netfilter-persistent  start
    netfilter-persistent  save
